### ISSUE TITLE
Creating metamodel from plugin loses metamodel tabs on refresh

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-engine#112]
When creating a metamodel programmatically (with multiple tabs), the tabs are available and everything behaves as expected until the page is refreshed. After the refresh, the tabs are not shown in the MetaModel editor in webgme.

Tthe newly created nodes are still members of the meta (they can still be instantiated in other visualizers) but cannot be found in the metamodel.

**Comment by pmeijer** [comment]
Can you check out `<host>/api/projects/:user/:projectName/branches/master/tree/` and look at the 'reg.MetaSheets'?

**Comment by brollb** [comment]
Cool, thanks. Are you creating new tabs in the metamodel also?

It puzzles me that it only disappears after refresh and works as expected until then.

**Comment by finger563** [comment]
though looking at your code it does seem to be using the same `id` type that i'm using :man_shrugging:

**Comment by pmeijer** [comment]
https://editor.webgme.org/developer/api#projects__ownerId___projectName__commits__commitId__tree__nodePath__get

Please check if there's a commit made by the meta-editor.

**Comment by brollb** [comment]
I attached the contents of the commit created by the plugin. I don't see any others but if I am missing something, let me know!
[commit.zip](https://github.com/webgme/webgme-engine/files/2207095/commit.zip)

**Comment by brollb** [comment]
Are the `_null_ptr`'s an issue?
![deepinscreenshot_kivalasztott terulet_20180718143506](https://user-images.githubusercontent.com/4982789/42903563-dbcf424c-8a97-11e8-95d3-7f52e6e6d250.png)

**Comment by pmeijer** [comment]
No. 
The problem is that the MetaSheets aren't showing up 
```
    "MetaSheets": [
      {
        "SetID": "MetaAspectSet_68f8146d-b1b7-6c40-3464-f8c070e97e8d",
        "order": 0,
        "title": "META"
      }
    ],
```
Which version of webgme are you using?

**Comment by pmeijer** [comment]
Remember you had an issue where you mutated the registry (since getRegistry returned reference to the data entry stored). This seems related. Are you running the plugin in the browser?

**Comment by pmeijer** [comment]
#17 takes care of that. But if you're running your current code against an older version and the plugin in running in the browser - the behavior could be something like in this issue.

**Comment by brollb** [comment]
2.19.0 (should have the fix)

**Comment by pmeijer** [comment]
https://github.com/webgme/webgme/blob/v2.19.0/package.json#L30
It's using engine 2.18.4 and the fix was in 2.18.5.
So either upgrade or make a copy of the sheets after you've retrieved the value.

**Comment by brollb** [comment]
I cloned webgme-engine and then symlinked that from node_modules (so I had the master branch version in the deps) and still had the issue.

**Comment by pmeijer** [comment]
You would have to rebuild the client distribution for that to work...
Alt. try via `/debug.html`

**Comment by brollb** [comment]
Nice - that fixed it! Thanks!

In case anyone else runs into this issue, the TL;DR version is to update webgme to a version using webgme-engine v2.18.5. (thanks @pmeijer)
