### ISSUE TITLE
JSON Payload Sizing

### ISSUE THREAD

**Issue by nawgszy** [webgme/webgme-engine#113]
Would it be possible to expose the configuration options for `bodyParser.json` somewhere? I have a router attached to the app which powers a graphing service, and when my project hits a large amount of nodes I can no longer make post requests to this router as `bodyParser` is using the default maximum payload size.

Since the middleware mounted by the app is always hit before the middleware mounted by the router, as well, I can't even put my own `bodyParser` options in the middleware without doing something ugly to make the request get ignored by the initial `bodyParser` the app spawns.

If there is some other strategy you know of to get around this, besides running my service as a separate express server, I would be happy to hear of that as well.

**Comment by brollb** [comment]
Are you sending the nodes to the router in the request? If so, have you considered simply passing the project ID, owner, etc, to the router (as the router has access to the storage layer). 

I have a [router](https://github.com/deepforge-dev/deepforge-keras/blob/master/src/routers/KerasAnalysis/KerasAnalysis.js) which seems somewhat similar; I am providing analysis feedback for a node in a project (using the subtree rooted at the given node) using a router. In that router, I am [ensuring that the user is authenticated](https://github.com/deepforge-dev/deepforge-keras/blob/master/src/routers/KerasAnalysis/KerasAnalysis.js#L54-L66) then actually running a [plugin to convert the model into the analysis code](https://github.com/deepforge-dev/deepforge-keras/blob/master/src/plugins/ValidateKeras/ValidateKeras.js) and [running it via the router](https://github.com/deepforge-dev/deepforge-keras/blob/master/src/routers/KerasAnalysis/KerasAnalysis.js#L130-L173).

**Comment by kecso** [comment]
Can you also detail the exact scenario a bit more?
BodyParser should not block noticeably even if the amount of data to parse is big. On the other hand if the router somehow extracts or try to extract too many nodes in a blocking manner, that can be an issue for simultaneous requests.

**Comment by nawgszy** [comment]
Sure.

I have a graph consisting of ~7000 nodes and a similar amount of edges. I send a simple list to a graph layout route I made from within a plugin, that just describes the edges of the graph by giving the node ID of the src and dst pointers of the edge.

Request body is:
```
{
  edges: [
    { src: '/a/b', dst: '/a/c' },
    { src: '/a/c', dst: '/a/d' },
    ...
  ],
}
```

This works with ~2000 nodes but seems to cap out somewhere before ~5000 nodes, I can try and find the more specific limit if it somehow proves necessary.

**Comment by nawgszy** [comment]
I fully understand if accepting this isn't within the best interests of webgme, but I can verify that this pull request fixed the issue for me.

**Comment by kecso** [comment]
I will check the pull request (checked it already).
It is not that it would be a problem to expose this, I just wanted to make sure that this is the real source of the issue!
I will suggest some minor changes (so that it might be a little bit more flexible and future proof), but overall: thanks!
