### ISSUE TITLE
How to: make a relation like a set, but with an additional piece of information

### ISSUE THREAD

**Issue by nawgz** [webgme/webgme-engine#130]
I have a modeling question.

Say I have a model where I am defining three things: `recipe`s, `item`s, and `material`s.

Each `recipe` can be fulfilled to create some `item`, which is simple enough: I can just use a pointer, or a connector.

However, in order to fulfill a `recipe`, you must collect and use `x_1` of `material_1`, `x_2` of `material_2`, etc.. 

As I would like to be able to update, rename, or remove a `material` and have any reference to the `recipe` correctly know all about each of the `materials`, a set seems like the natural fit.
 
However, I do not want `x_i` to be 1 for each material, which seems to me the only way I can do this with a set.

I could see connectors somewhat fulfilling this role, but the `set` concept maps perfectly onto this idea besides the omitted `quantity` value.

How would you suggest this be done?

**Comment by pmeijer** [comment]
1. You can use connections (connectors) between `recipe`s and `material`s and add an integer "quantity" attribute with range `[0, Inf)` or `[1, Inf)`.

2. You can store [set-member registries/attributes](https://editor.webgme.org/docs/source/Core.html#setMemberAttribute__anchor) for members of a set. 
Such attributes aren't exposed in the generic GUI as there is no corresponding meta-definition for them. Therefor there is currently no way to enforce or check the validity of the given value based solely on the metamodel. 
I know there has been discussion about extending the "metameta-model". I like the idea, but I also see the added complexity they would introduce. I know of other use-cases for such attributes and in those cases they are only displayed/(editable in a constrained fashion) in the domain specific visualization and evaluated at the point of model-interpretation.

**Comment by nawgz** [comment]
Ah great, I have played with node registries before and understand exactly what you're saying with the set registries and lack of built-in checks, but despite the minor issue of validation the simplicity of that idea will work perfectly for me. I have an entirely custom UI so the lack of generic support will not be an issue. Thanks!
