### ISSUE TITLE
Strategies for checking if a seed can be updated?

### ISSUE THREAD

**Issue by nawgz** [webgme/webgme-engine#133]
I lifted some code out of `webgme` itself that checked if a library could be updated, which looks like this:

```
checkForUpdate(libraryName) {
  const { client } = GME;
  const libraryInfo = client.getLibraryInfo(libraryName);

  // I stole this logic almost directly from LibraryManager
  if (libraryInfo && libraryInfo.projectId && libraryInfo.branchName) {
    client.getBranches(libraryInfo.projectId, action((err, branches) => {
      if (err) {
        console.error('Failed to checkForUpdate', err);
        return false;
      }

      if (
        branches[libraryInfo.branchName]
        && branches[libraryInfo.branchName] !== libraryInfo.commitHash
      ) {
        return true;
      } else {
        return false;
      }
    }));
  }
}
```

However, now I am running into an issue where I get 'Not authorized to read project [GLOBAL+SEED]', where GLOBAL is an organization I set up and SEED is the Library, obviously. To be honest, I'm not quite sure how this project became owned by the GLOBAL organization, since I generated a .webgmex file from a default instance of WebGME and used that as the seed.

But ultimately, the question is: is there some built-in way to check for this, or is this the only strategy? If the latter, I am sure I can unravel the permissions here, but it would be nice to know I was doing it right.

**Comment by pmeijer** [comment]
If you exported a project with a library linked to project on one deployment - the link isn't redirected when you import it at another deployment. 
The error `'Not authorized to read project [GLOBAL+SEED]'` is most likely logged when trying to getBranches of a non-existing project (the error message is purposefully constructed that way in order to hide information about the others' projects).

If you want to link to a project on your deployment, the best way is to export the library from "default instance of WebGME" and import it onto your deployment. And for the project containing the library - select update library, choose the URL-tab and copy-paste the intra-deployment URL to the library uou imported.

The LibraryManager was not added to the client API as the code is coupled with visualization. Although you raise a good point highlighting that some of the logic should be extracted.

**Comment by nawgz** [comment]
I exported the seed from one deployment, but never the projects. I then register the seeds in `config.webgme.js` via
```
config.seedProjects.basePaths.push(path.join(__dirname, '/../common/seeds/SEED'));
```
Which contains the file `SEED.webgmex`. Then I try to run the function above like
```
const shouldUpdate = checkForUpdate(libraryName);
```

But it always errors in the `client.getBranches` call with the error I gave. It seems strange that I would get `libraryInfo` back from the `client.getLibraryInfo` call with a `projectId` that doesn't exist. Is it possible that there are some permissions set on the initial WebGME deployment where I generate that would restrict access?

**Comment by pmeijer** [comment]
Seeds are "snapshots" of projects in that they represent the state of a project at a specific commit. 
Intra-deployment linked libraries stores the owner, project-id, branch-name and commit-hash of a project on the same deployment. If you export a snapshot of a project with such internal links - they will not resolve correctly at any other deployment. As I mentioned above, in case you want to resolve these links at a new deployment you need to import both seeds into projects at the new deployment and update the library to link to that project. If you want to cut the link completely, you can update the library from a file-seed.

```
It seems strange that I would get libraryInfo back from the client.getLibraryInfo call with a projectId that doesn't exist.
```
The error, `'Not authorized to read project [GLOBAL+SEED]'`, is not a hard error - it just means you cannot proceed with following the library. It's what's telling you that a project with that id does not exist.

**Comment by nawgz** [comment]
I see now. We talked about this on another issue too, where you recommended I make the seed an empty project that has the meta-model included as a library already, as opposed to importing the seed into a brand new empty project as a library each time, and I understand why that is the better strategy. Thanks again, your responsiveness is appreciated.
