### ISSUE TITLE
How to use client.copyNodes?

### ISSUE THREAD

**Issue by nawgz** [webgme/webgme-engine#157]
Hi, I am trying to implement copy-paste and it is quite unclear to me what the intended workflow here is.

Here's a few things I saw and tried:
From digging around the `webgme` (not `webgme-engine`) source, I found TreeBrowserWidget code (in /webgme/src/client/js/Widgets/TreeBrowser/TreeBrowserWidget.Keyboard.js) that had a `switch` statement with options like 'ctrl+v' and 'ctrl+c', and so while that looked promising, the 'ctrl+v' option had a function `this._nodePaste`. That didn't seem to lead anywhere, as, In the end, I full-text searched the code base to follow that around:
```
line 179   this._nodePaste(node) 
                    /webgme/src/client/js/Widgets/TreeBrowser/TreeBrowserWidget.Keyboard.js
line 692    TreeBrowserWidget.prototype._nodePaste    /webgme/src/client/js/Widgets/TreeBrowser/TreeBrowserWidget.js
```
and that function called `this.onNodePaste` which does not exist (so I am guessing was intended to be defined by whoever extended the TreeBrowser). No problem.

I found another promising lead, in /webgme/src/client/js/Panels/ModelEditor/ModelEditorControl.DiagramDesignerWidgetEventHandlers.js line 869:

```
ModelEditorControlDiagramDesignerWidgetEventHandlers.prototype._onClipboardPaste = function () {
          if (this.currentNodeInfo.id) {
             this._client.pasteNodes(this.currentNodeInfo.id);
         }
     };
```

But in the end I could not find any function named `pasteNodes` in `webgme` or `webgme-engine`.

Finally, I hoped to use `client.copyMoreNodes` to copy an array like so:
```
const nodesToCopy = ["/y/U/l4", "/y/U/Xd", "/y/U/wO", "/y/U/x1", "/y/U/zm"];
```
To form an object
```
const parameters = {
  y/U/I4: {},
  /y/U/Xd: {},
  /y/U/wO: {},
  /y/U/x1: {},
  /y/U/zm: {},
  parentId: "/y/U",
};
```
To invoke as
```
client.copyMoreNodes(parameters);
```
But this, despite being dynamically generated with the activeNode set to `/y/U`, by a user dragging a box over the nodes to form that selection I pasted as `nodesToCopy` here, reached the `else` statement in client.copyMoreNodes (/webgme-engine/src/client/gmeNodeSetter.js) and fired `state.logger.error('wrong parameters for copy operation - denied -');`.

Ultimately, my question is simple: in the default webgme UI, with the the 'Composition' Visualizer selected, I can click a node (or nodes), press "cmd + c" and "cmd + v" to copy paste the nodes. I couldn't figure out what functions or what source code to look through to understand how this operates, and I hit a few dead ends. Can you provide some guidance? Thanks.

**Comment by pmeijer** [comment]
I've added documentation strings in #158 and the example in the ModelEditor is https://github.com/webgme/webgme/pull/1676/files inside (`_onPaste`)

**Comment by pmeijer** [comment]
Your
 ```const parameters = {
  y/U/I4: {},
  /y/U/Xd: {},
  /y/U/wO: {},
  /y/U/x1: {},
  /y/U/zm: {},
  parentId: "/y/U",
};```
look right to me. The only thing I can think of why it wouldn't work is that the nodes to copy aren't loaded in the client, that is part of a territory.
