### ISSUE TITLE
Importing From GME

### ISSUE THREAD

**Issue by mChron** [webgme/webgme-engine#162]
We are working towards a migration from GME in the windows environment to WebGME deployed via Docker containers. In doing some digging I found the parse_xme.js utility but it seems it's outdated. Is there any expectation of reviving work on that? Or is there some other route I can take for importing a project from GME (other than manually recreating it)? I also tried working with an xmltojson converter but that didn't go far. Any insight would be greatly appreciated.

**Comment by kecso** [comment]
We have left the idea of a generic translator for GME->WebGME as there is no simple one-to-one mapping and it heavily depends on the domain what features should be used in the WebGME depiction.
So what I would advise is to do the metamodelling by hand (of course it depends on the size of your metamodel) and then creating an importer that can consume old GME models.

We can certainly help on getting these done. As far as generic importer/translator, I do not see it happening as there are not too many projects that have the number of models that would justify the effort of developing a generic solution.

**Comment by mChron** [comment]
@kecso Thanks for your input. We may take a stab at creating an importer, but ultimately may have to handcraft our existing models. If we do go down the path of creating an importer I may reach out for any issues we're having. Thanks!
