### ISSUE TITLE
Plugin Api For Specific Plugin Returning Not Found

### ISSUE THREAD

**Issue by mChron** [webgme/webgme-engine#163]
I'm running the webgme/webgme-org:2.33.0 docker image.

I'm trying to invoke my plugin via the rest API but haven't had much luck.
So I backtracked and I'm trying to view the metadata of my custom plugin. .../api/plugins shows me the list of plugin names just fine.
But if I try something like .../api/plugins/AddOnGenerator/metadata I'm getting a 404 return status. Tried on several other built in plugins and I'm seeing the same result.
@pmeijer or @kecso  Any ideas?

**Comment by kecso** [comment]
That information is not meant to be gathered via regular http protocol. It is a safety feature, that only some static content can be directly downloaded.
To make sure you have the correct info, you need to debug the plugin from a regular browser during regular function (executing on the client-side as in that case those metadata will be downloaded).

On the other hand, invoking should not be connected directly to the metadata. If you send some detailed info about the issue, I might be able to point out, what could be wrong...

**Comment by mChron** [comment]
So @kecso in order for me to actually invoke my plugin (e.g. a POST to localhost:8000/api/plugins/myPlugin/execute) I would have to host my container over https?

**Comment by kecso** [comment]
Yeah, sorry I got it wrong.
https://editor.dev.webgme.org/api/plugins/metadata
This worked for me, I will check the specific one (it might be authentication issue, though I believe in that caser the error should be different)

**Comment by kecso** [comment]
and no, you do not need to host over https. what I was referring to, is that regular http request (not the /api calls) should only retrieve some basic static content.

**Comment by kecso** [comment]
I also tried https://editor.dev.webgme.org/api/plugins/AddOnGenerator/metadata, and it worked.
It is definitely weird how the listing works, but this call would not...

**Comment by mChron** [comment]
@kecso Oh sorry, I misunderstood. Right, both /api/plugins and /api/plugins/metadata work for my container instance, but trying to get the metadata of a single plugin using it's Id returns a 404

**Comment by kecso** [comment]
It seems weird, but there was an update lately (5 months ago) to those requests that should not be functional.
So, first I would advise to use the latest version (checkout webgme repository and build the dockers with the docker-compose...). if that still does not work I will have to replicate your environment to give further assitance.
Another option could be to try /api/plugin/pluginId/metadata (singular instead of plural).

**Comment by mChron** [comment]
@kecso Just tried singular /api/plugin/AddOnGenerator/metadata and that worked. Tested out my POST requests using singular and those worked as well. Thanks for your help!

**Comment by kecso** [comment]
Anytime! (I would still advise trying to move to the latest as soon as possible...)
