### ISSUE TITLE
Should Access Tokens hide their value after creation?

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-engine#188]
It seems that it might be beneficial to hide the value of personal access tokens after creation (as done with GitHub personal access tokens and other projects). A couple benefits:
- Promotes creation of more tokens (rather than reusing a single token for many things which would be less secure)
- More difficult to steal the token values as they are only shared with the user once

I don't think it is necessary but there seem to be a few benefits without any obvious drawbacks. What does everyone else think?

**Comment by umesh-timalsina** [comment]
This will beneficial if the tokens are meant to serve a single purpose. For example, in `github` when you create a secret, it is usually meant for a single purpose -> Authentication for tests in CI, Deployment Keys etc... and once set they don't usually change.

**Comment by kecso** [comment]
I suggested the same to Umesh in regards to the user management page.
I am all for it, but we need to make sure that our REST API and UMP are in sync in regards to this feature.

**Comment by brollb** [comment]
Sounds good. In that case, I will update the access tokens to omit the token value when listing them so the value of the token is only available in the token returned on creation.
