### ISSUE TITLE
`core.setBase` appears to remove existing children in the node

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-engine#236]
When using `core.setBase` on some instance node which already contains children. I expected this to leave the existing nodes...

**Comment by kecso** [comment]
You need to be a bit more specific.
The functionality is expected to remove everything that was inherited from the original base, including children.

**Comment by brollb** [comment]
Here is a failing test:
```javascript
it.only('should not delete children when setting base', async function() {
    const fco = await core.loadByPath(root, '/1');
    const newBase = core.createNode({base: fco, parent: root});
    const node = core.createNode({base: fco, parent: root});
    /*const childNode = */core.createNode({base: fco, parent: node});
    core.setBase(node, newBase);
    assert.equal(
        core.getChildrenPaths(node).length,  // this is 0. Expected 1
        1
    );
});
```

**Comment by kecso** [comment]
Well,
I was wrong and the behavior is much more complicated.
So:
- when setting the base, we drop the purely inherited children (meaning nothing was changed compared to their base)
- we keep those inherited child that came from the original base, has some change 
- we drop everything else (including purely new children...)

that means, that the behavior is as expected in your testcase...
we can go through on the functionality and try to enhance it, but as of now this is functions according to design

**Comment by brollb** [comment]
Gotcha. Maybe I will change this to a "discussion" instead :) I will update my code accordingly. Thanks!
