### ISSUE TITLE
Cannot execute browser plugin in unloaded node

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-engine#238]
I ran into some slightly odd behavior and wanted to make an issue to make sure it was the desired behavior. When running a browser plugin programmatically where the active node is set to a node that has not been loaded by the client, I get an error (`Cannot call getOwnRegistry of undefined`):
![DeepinScreenshot_select-area_20201012172119](https://user-images.githubusercontent.com/4982789/95796329-318d7c00-0cb2-11eb-959f-5022783ffd39.png)

If this is the expected behavior, it should at least give a better error message in pluginmanager.js

**Comment by kecso** [comment]
I believe this is intended, but you are right in that it should throw a better error telling that you need to have your node ready to call a plugin on it.
