### ISSUE TITLE
Access project model/nodes using REST API

### ISSUE THREAD

**Issue by Ayman-Meidan** [webgme/webgme-engine#263]
Hello,
Is it possible to access the project model/nodes using REST API (as we do using plugins) to:

-Collect data from models and nodes
-Edit the model

I've checked the available rest APIs, but couldn't find any that allow these functions.

Thanks in advance

**Comment by kecso** [comment]
That is not possible as there is no public exchange format for the model data.
Usually you write a plugin that can output the format you want.
