### ISSUE TITLE
Using `text!` requirejs plugin fails on node 8

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-engine#32]
When using node 8 and trying to run plugin tests, I started getting a bunch of errors about not being able to load 'text' (trying both requirejs and node's require). Deleting and reinstalling node_modules didn't fix it but switching down to node v6 did... 

I tried to replicate it with a new project but didn't have any luck. 
![deepinscreenshot_select-area_20171216124102](https://user-images.githubusercontent.com/4982789/34073894-0b516b2a-e26a-11e7-9d35-2f845ca7d46f.png)
I am not sure of the exact cause but thought it was worth an issue.

**Comment by pmeijer** [comment]
Which version of webgme and webgme-engine are you using?
I'm surprised it looks for the text in the `client/lib`...

https://github.com/webgme/webgme-engine/blob/master/index.js#L33

**Comment by brollb** [comment]
here is an example of it failing on travis with the given error message: https://travis-ci.org/deepforge-dev/deepforge/builds/326543243

**Comment by pmeijer** [comment]
This is no longer needed: https://github.com/deepforge-dev/deepforge/blob/master/test/globals.js#L32-L36

It was initially added in this pull request (and updated in the engine repo):
https://github.com/webgme/webgme/pull/960/files#diff-8e38b4e0a0bfe8e110422986d4f74709R21

**Comment by brollb** [comment]
my bad! Thanks!
