### ISSUE TITLE
client 'state' seems to forget about nodes

### ISSUE THREAD

**Issue by nawgszy** [webgme/webgme-engine#68]
For context, I am making a new (React) UI in front of WebGME.

To load nodes, I use ```client.addUI```, ```client.updateTerritory```, and ```client.removeUI```. After the ```updateTerritory``` call triggers, my loading function gives me a local reference to the ```GMENode``` object via ```client.getNode(loadedPath)```.

This also means that the ```client```'s internal ```state``` object has the node available at ```state.nodes[loadePath]```, which is obviously crucial for all methods on the ```GMENode```.

At this point, I fully expect to be able to use all of the ```GMENode``` functions as described in the ```GMENode``` generated docs, as well as all the ```client``` functions, especially ```client.setRegistry```

I create a React component with an ```onMouseMove``` function, which looks like this (```node``` is a ```GMENode```!)
```
onMouseMove(e) {
    const { client, eventManager, node } = this.props;
    const mousePos = eventManager.getMousePosition(e);
    const lastPos = this.dragState.lastPos;

    const mouseDelta = {
      x: mousePos.x - lastPos.x,
      y: mousePos.y - lastPos.y,
    };

    const nodePos = node.getRegistry('position');
    const newPos = {
      x: nodePos.x + mouseDelta.x,
      y: nodePos.y + mouseDelta.y,
    };

    client.setRegistry(node.getId(), 'position', newPos);
    // this function causes a rerender
    eventManager.updated();

    this.dragState.lastPos = mousePos;
}
```

The first time this event fires, it seems to successfully move the node; all subsequent times, I get an error:

```
gmeNodeGetter.js:121 Uncaught TypeError: Cannot read property 'node' of undefined
    at GMENode.getRegistry (gmeNodeGetter.js:121)
    at Node.onMouseMove (Node.js:181)
```

And when I look into the client ```state``` object (by calling ```console.log(client.getNode('')._state.nodes)```, I see that the node which I tried to move no longer is registered within the state.

Can you help me understand what I need to do to correctly update the node's registry without causing caching issues?

PS: Thanks a lot for the software, by the way, it is really great, even if the only time I ever seem to interact with you is when I have issues!

**Comment by kecso** [comment]
There are multiple ways to solve the issue, but here are some markers in general:
- when you call any update function (like setRegister), that causes a commit
- after a commit all GMENode objects became invalid
- as a UI piece, your next possible interaction point is when your event function is being called letting you know which nodes have been updated.

Having said that, I would strongly recommend to separate the onscreen position from the object's position and only change the object when the dragging stops (if that is a dragging).

Your approach could still work, but you need to check if your component got any event update before the next onMouseMove event and you need to getNode every time to keep your GMENode object up to date (so if multiple mouse event fire without receiving the necessary event callbacks from the client you are out of luck).

If you are not worried about collaborative issues, you can also start a transaction as that way your registry update will not trigger a commit and you can keep updating the registry until you see that a commit is required to notify other users about what is going on on the screen (this solution is not preferred as it has its drawback when it comes to collaboration...).

If you are dealing with React, https://github.com/webgme/webgme-dss is worth your attention. It is a new implementation though, so there are some crude edges here and there, but if you know what you are looking for, you might find it :). Eventually we will revise the components and create some boilerplate and library.

I hope this helps!

p.s.: Thanks for the feedback, I hope we will continue earning it!

**Comment by nawgszy** [comment]
I will definitely check out your repository and see what there is to learn.

I do want to preserve the collaborative nature so I will try to avoid hanging transactions.

I guess my next question would be this: I was hoping simply to use the ```client``` class as my singleton data store, but it seems I would be better off constructing my own and then merging in any updates that happen with each commit.

Is it possible to see if a node has updated? For example, does each node have a hash which updates when it changes? For example, this way, when each commit occurs, I could make a call to ```client.updateTerritory``` to load any nodes I am interested in, and then perform a simple update such as

```
myCachedNodes.forEach((myCachedNode) => {
  const gmeNode = gmeClient.getNode(myCachedNode.id);

  if (gmeNode.getHash() !== myCachedNode.hash) {
   myCachedNode.update(gmeNode);
  }
})
```

Also, are there any sources of documentation which outline the inner GME logic such as you listed above (i.e "after a commit all GMENode objects become invalid")? I have read thru most of the available documentation (i.e. the generated docs, both source and REST, as well as the [Wiki](https://github.com/webgme/webgme/wiki), so I'm just curious if I'm missing anything or if this is just a product of webgme-engine being quite new.

**Comment by kecso** [comment]
https://github.com/webgme/webgme/wiki/GME-Client-API

There are definitely gaps in the documentation, and that is most visible when someone tries to attack an issue with a completely new set of mind. It is not that you missed something, it is more, that those documentations usually has the best practices described that fulfill the needs of most users.
As much as the core API has a detailed function level description, unfortunately the client still misses that one.

So if you develop a UI component, then you work with a territory. By setting a territory, you technically list the nodes you are interested in. Afterwards you always 'react' whenever your eventHandler function is called (which happens after every change, you might not get actual updates if none of your nodes have changed).
In a way, this means that your singleton entry point for data is the client. You just have to accept the fact, that it is state-full and that you should not hold on to the node references.
(The react analogy would be that the container of your component might drive your component into a new state, while your component getting into a new state does not automatically sends the container anywhere and you manually have to notify it, and when you do, you first want to handle its response...)

**Comment by nawgszy** [comment]
Thanks for being so responsive. I believe I am understanding better, so I have one question about how ```updateTerritory``` behaves.

Say I have a class like 

```
class NodeStore {
  UI_ID = 'nodeStore';
  activeNode = null;
  
  // what will be the pattern passed to onTerritoryUpdated ?
  constructor() {
    this.client = new GME.classes.Client(...);

    this.client.addUI(null, this.onTerritoryUpdated, this.UI_ID);
  }

  initialize() {
    // a promise calling client.connectToDatabase, client.openProject, etc
  }

  onNodeClicked(node) {
    const nodeId = node.getId();
    const childLoadingPattern = {};
    childLoadingPattern[nodeId] = { children: 1 };

    this.client.updateTerritory(this.UI_ID, childLoadingPattern);
  }

  onTerritoryUpdated(events) {
    // does events contain only the latest childLoadingPattern?
    // or does it contain all of the nodes I've ever requested to be loaded via updateTerritory
    const loadedNodeIds = events.filter((event) => typeof event.eid === 'string').map((event) => event.eid);

    // now for exactly each nodeId in loadNodeIds I can call client.getNode and functions on that GMENode, correct?
  }
}
```

Hopefully this is clear. There are two questions here:

1. After a commit, the territory will update. I believe it won't pass just the latest ```childLoadingPattern```, but all ```childLoadingPattern```s I have registered via ```this.client.updateTerritory(this.UI_ID, childLoadingPattern)```, correct? And, accordingly, if I wanted to only load the latest, for each onNodeClicked I could say 

```
this.client.removeUI(this.UI_ID);
this.UI_ID = this.client.addUI(null, this.onTerritoryUpdated);
```

2. Exactly the node IDs I put into ```loadedNodeIds``` in my ```onTerritoryUpdated``` call are the nodes which I can access from ```client.getNode``` and call the methods of, correct? Or will ```loadedNodeIds``` not include the META and ROOT nodes even if they will still be available?

I hope these questions make sense! Let me know if I need to phrase them more clearly or flesh out my example.

**Comment by kecso** [comment]
so just a few comments, that might make things more clear:
- the client is a singleton (so probably you only need one per client)
- updateTerritory sets the territory of the given UI component (it is a json object check out the wiki page for an example) as you only have a single descriptor, only your last one will be active
- also keep in mind this is an update so if you would go from [a,b] -> [c], that would already generate two unload and one load events (as you need to take care of removing a and b from your visualization)
- so usually the territory does not changes unless it is really necessary
- in the eventManager function you can receive 'technical'/'load'/'update'/'unload' events
 - technical you should not worry about as it only highlights that a batch of eventing is complete or you can expect some more regarding the given state of the project
- load means you need to add your visual depiction of the given node
- unload means that it will be no longer available so remove every reference 
- update, something changed so you need to check if you have to update your visuals regarding the node
=> you need to have your own list about the nodes that you think are available
=> once this eventManager function is called, you can try getNode on all the nodes that your territory has

Also, a good practice might be to simply call the getNode functions as a result of the eventManager, but test if it really a GMENode or just null (which means that at the moment the node is not loaded to the client or there is no such node).

another example: https://github.com/webgme/webgme/blob/master/src/client/js/Panels/ObjectBrowser/TreeBrowserControl.js
(not react but you can see how the territory is managed and how the updates are handled)

So although it is not crystal clear what the intention of the class is, but generally it does not seems to be bad (other than the 'client' should more be a parameter of the class...), but you will need your own dataset that you use in your visualization.

**Comment by nawgszy** [comment]
Great, that's plenty to work with for now. It was mostly a device to get an answer something like the one you just gave me, so thanks again!
