### ISSUE TITLE
Unable to import model if model's meta is a library and vice versa

### ISSUE THREAD

**Issue by finger563** [webgme/webgme-engine#86]
Don't know a good title description - but here are the use cases:

* Have an original deployment of a domain - where the meta is *not a library*
* Have another deployment where the original domain's meta *is a library*

I have two models (below - they were renamed from `.webgmexm` to `.zip`)

[HFSM_exported_from_webgme-rosmod.zip](https://github.com/webgme/webgme-engine/files/1948883/HFSM_exported_from_webgme-rosmod.zip)
[HFSM_exported_from_webgme-hfsm.zip](https://github.com/webgme/webgme-engine/files/1948884/HFSM_exported_from_webgme-hfsm.zip)

The meta is the same whether its in the domain as a library or in its own model. In either deployment - i cannot import a model from the other deployment.

Below are some screenshots from trying to do it:

![image 3](https://user-images.githubusercontent.com/213467/39273550-c0523806-48a4-11e8-9fa8-c1f4cb99faf4.png)
![image](https://user-images.githubusercontent.com/213467/39273553-c08a1a78-48a4-11e8-900b-b29b0551b50e.png)
![image 2](https://user-images.githubusercontent.com/213467/39273551-c0645766-48a4-11e8-91ac-0d1641a3f594.png)
![image 1](https://user-images.githubusercontent.com/213467/39273552-c0777080-48a4-11e8-970c-0d961df89a57.png)

**Comment by finger563** [comment]
Thanks for the response - though it actually happens for me even when the library is not embedded within another one - can show that if you'd like some reproduction of the issue

**Comment by kecso** [comment]
hmm. I might missed something during debug.
I'll cook up some test-cases and let you know.
Anyhow, if everything goes fine, you get your fix and enhancement as well :)

**Comment by finger563** [comment]
w00t
